version: '3'

services:
  redis:
    image: redislabs/redismod:latest
    container_name: redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
  
  redis-insight:
    container_name: redis-insight
    image: redislabs/redisinsight:latest
    ports:
      - "13333:8001"
    depends_on:
      - redis
    links:
      - redis
    
volumes:
  redis-data: